--- image-0.3.0/Makefile	2010-07-29 19:35:58.297827605 +0200
+++ image-0.3.0/Makefile	2010-07-29 19:53:30.917848286 +0200
@@ -78,7 +77,7 @@
 DEFINES  += -D_GNU_SOURCE
 LIBS += liboutput/liboutput.a libimage/libimage.a

-INCLUDES += -I$(VDRINCDIR) -I.
+INCLUDES += -I$(VDRDIR)/include -I.

 ifdef FFMDIR
 DEFINES += -DFFMDIR
@@ -183,7 +183,7 @@
 	@for i in $(SUBDIRS) ;\
 	do \
 	    ( cd $$i;\
-              $(MAKE) all;\
+              $(MAKE) all PLUGIN=$(PLUGIN);\
        ) \
 	|| exit 1;\
 	done
