--- image-0.3.0/Makefile	2010-07-29 19:35:58.297827605 +0200
+++ image-0.3.0/Makefile	2010-07-29 19:53:30.917848286 +0200
@@ -183,7 +183,7 @@
 	@for i in $(SUBDIRS) ;\
 	do \
 	    ( cd $$i;\
-              $(MAKE) all;\
+              $(MAKE) all PLUGIN=$(PLUGIN);\
        ) \
 	|| exit 1;\
 	done
